[package]
name = "circe"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
nftnl = { path = "nftnl/nftnl", features = [ "query" ] }
lazy_static = "1.4.0"
thiserror = "1.0"
mnl = "0.2.0"
libc = "0.2"
tracing = "0.1"
tracing-subscriber = "0.2"
