network = "192.168.42.1/24"
bridge_name = "circe"
listening_port = 8000

[[sites]]
container_name = "a"
source_port = 512
container_ip = "192.168.42.5"
destination_port = 2048
connection_treshold = 5
