[package]
name = "circe_launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
circe_common = { path = "../circe_common", features = ["toml_support", "net"] }
qapi = { version = "0.8.0", features = [ "qmp" ] }
serde_json = "1.0"
